version: '2'
services:
  cassandra-node1:
    image: bitnami/cassandra:latest
    ports:
      - '7000:7000'
      - '7001:7001'
      - '9042:9042'
      - '9160:9160'
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
  cassandra-node2:
    image: bitnami/cassandra:latest
    ports:
      - '7000:7000'
      - '7001:7001'
      - '9042:9042'
      - '9160:9160'
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
  cassandrawriter:
    image: "sghintala/cassandra-writer:latest"
    container_name: "cassandrawriter"
    links:
      - "cassandra-node1:cassandrahost"
    depends_on:
      - cassandra
    environment:
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_USER=cassandra
      - CASSANDRA_HOST=cassandrahost
volumes:
  cassandra_data1:
    driver_opts:
      repl: '3'
      size: '2'
    driver: pxd
  cassandra_data2:
    driver_opts:
      repl: '3'
      size: '2'
    driver: pxd


