version: '2'
services:
  postgresdata:
    image: "postgres"
    container_name: postgresdata
    volumes:
      - /mariadb_data:/var/lib/postgresql/data
    command: /bin/true
    
  postgresdb:
    image: "harshals/mypostgres:1.4"
    container_name: postgresdb
    volumes:
      - /mariadb_data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=mypguser
      - POSTGRES_DB=flktstdb
  pgwriter:
    image: "harshals/postgreswriter:1.3"
    container_name: "pgwriter"
    links:
      - "postgresdb:postgres"
    depends_on:
      - postgresdb
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=mypguser
      - POSTGRES_DB=flktstdb
      - POSTGRES_TABLE=flockertab
      - POSTGRES_HOST=postgres
  web:
    restart: always
    container_name: "web"
    image: "harshals/web:1.0"
    expose:
      - "8000"
    links:
      - "postgresdb:postgres"
    depends_on:
      - pgwriter
    volumes:
            - /ngnix:/usr/src/app/static
    env_file: ./config/.env
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

  nginx:
    container_name: "ngnix"
    restart: always
    image: "harshals/nginx:1.0"
    ports:
      - "80:80"
    volumes:
      - /ngnix:/www/static
      - /ngnix:/usr/src/app/static
    links:
      - "web:web"
volumes:
  mariadb_data:
    driver_opts:
      repl: '1'
      size: '2'
    external: true
    driver: pxd
  ngnix:
    driver_opts:
      repl: '1'
      size: '2'
    external: true          
    driver: pxd

