version: '2'
services:
  cassandra:
    image: 'bitnami/cassandra:latest'
    ports:
      - '7000:7000'
      - '7001:7001'
      - '9042:9042'
      - '9160:9160'
    volumes:
      - 'cassandra_data_standard:/bitnami'
  cassandrawriter:
    image: "sghintala/cassandra-writer:latest"
    container_name: "cassandrawriter"
    links:
      - "cassandra:cassandrahost"
    depends_on:
      - cassandra
    environment:
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_USER=cassandra
      - CASSANDRA_HOST=cassandrahost
volumes:
  cassandra_data_standard:
    driver_opts:
      repl: '3'
      size: '2'
    driver: pxd


